server:
  port: 9000

spring:
  application:
    name: res-eureka-9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

